#本地控制端口
[ctlserver]
address='0.0.0.0'
port=5090


#rtu上连端口（需开放外部端口,用于rtu接入）
[rtuserver]
address='0.0.0.0'
port=50080

#本地websocket控制端口
[webserver]
address='0.0.0.0'
port=5070

#代理服务器端口
[rmtserver]
address='0.0.0.0'
#本地访问映射端口组
localport=[6001,6200]
#远程接入端口组（需开放外部端口,用于rtu接入）
proxyport=[50101,50300]
