[[org]]
org='jdrk'
name='建大仁科'

[[org]]
org='shhl'
name='上海华立'


[[iothelp]]
org='jdrk'
type='rain'
name='雨量计'
mode=''
file='jdrk-rain.toml'


[[iothelp]]
org='shhl'
type='elecva'
name='电表-A相电压'
mode='DTSD7738'
file='shhl-elecva.toml'

